CREATE TABLE IF NOT EXISTS users (
  id          BIGINT         NOT NULL  AUTO_INCREMENT PRIMARY KEY,
  email       VARCHAR(255)   NOT NULL  UNIQUE,
  password    VARCHAR(255)   NOT NULL,
  created_at  TIMESTAMP      NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP      NOT NULL  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id          BIGINT         NOT NULL  AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(255)   NOT NULL,
  price       BIGINT         NOT NULL,
  created_at  TIMESTAMP      NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP      NOT NULL  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id          BIGINT         NOT NULL  AUTO_INCREMENT PRIMARY KEY,
  user_id     BIGINT         NOT NULL,
  product_id  BIGINT         NOT NULL,
  created_at  TIMESTAMP      NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP      NOT NULL  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id)    REFERENCES users    (id),
  FOREIGN KEY (product_id) REFERENCES products (id)
);